# This file was generated by GoReleaser. DO NOT EDIT.
class GtsBio < Formula
  desc "GTS: the Genomics Tools Suite"
  homepage "https://github.com/go-gts/gts"
  version "0.9.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/go-gts/gts/releases/download/v0.9.6/gts_0.9.6_Darwin_x86_64.tar.gz"
    sha256 "ff9707c1ae1e555d0140cd5594cd59f28da2d04f12f63b7cdfa1324878955a55"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/go-gts/gts/releases/download/v0.9.6/gts_0.9.6_Linux_x86_64.tar.gz"
      sha256 "b6ca78871b8402f5ef9e1d004a329608dad4eb752f877de5ece99702a0d1e594"
    end
  end
  
  depends_on "go" => :build

  def install
    bin.install "gts"
    bin.install "togo"
  end

  test do
    system "#{bin}/gts --version"
  end
end
