# This file was generated by GoReleaser. DO NOT EDIT.
class GtsBio < Formula
  desc "GTS: the Genomics Tools Suite"
  homepage "https://github.com/go-gts/gts"
  version "0.10.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/go-gts/gts/releases/download/v0.10.1/gts_0.10.1_Darwin_x86_64.tar.gz"
    sha256 "7c7d55374fe5d57a2a0cca731623799ae2efbe2123e877b6c43b28ee31b92395"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/go-gts/gts/releases/download/v0.10.1/gts_0.10.1_Linux_x86_64.tar.gz"
      sha256 "9d168dfbdcf2af6c8137d41c0e5550676801bb296e555a66f6ebeecedf6d5962"
    end
  end
  
  depends_on "go" => :build

  def install
    bin.install "gts"
    bin.install "togo"
  end

  test do
    system "#{bin}/gts --version"
  end
end
