# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GtsBio < Formula
  desc "GTS: Genome Transformation Subprograms"
  homepage "https://github.com/go-gts/gts"
  version "0.27.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/go-gts/gts/releases/download/v0.27.1/gts_0.27.1_Darwin_x86_64.tar.gz"
    sha256 "66191efbfee6b74babbd58029630d2b7d02732f2f191d83156e209d41a359b36"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/go-gts/gts/releases/download/v0.27.1/gts_0.27.1_Darwin_arm64.tar.gz"
    sha256 "a4efe031058c3d6ea8217e57a64c0c20fe5571e6726be352041181a42544823b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/go-gts/gts/releases/download/v0.27.1/gts_0.27.1_Linux_x86_64.tar.gz"
    sha256 "3446919d57dda07cabccb43e3e0bf543d8d18d4af7c82f107ce24cb3a664a14d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/go-gts/gts/releases/download/v0.27.1/gts_0.27.1_Linux_arm64.tar.gz"
    sha256 "b045989b40580da53a5c1355f3bedd3cf2168497ba3ec5673b26535dbaa32b66"
  end

  def install
    bin.install "gts"
    bin.install "togo"
    man1.install Dir["man/gts*.1"]
    man7.install Dir["man/gts*.7"]
    bash_completion.install "completion/gts-completion.bash"
    zsh_completion.install "completion/gts-completion.zsh" => "_gts"
  end

  test do
    system "#{bin}/gts --version"
  end
end
