# This file was generated by GoReleaser. DO NOT EDIT.
class GtsBio < Formula
  desc "GTS: the Genomics Tool Suite"
  homepage "https://github.com/go-gts/gts"
  version "0.9.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/go-gts/gts/releases/download/v0.9.5/gts_0.9.5_Darwin_x86_64.tar.gz"
    sha256 "d38998cca24bf078c1613e8737efbdb779f476f4a70bcee37bf28c6ba70b67cc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/go-gts/gts/releases/download/v0.9.5/gts_0.9.5_Linux_x86_64.tar.gz"
      sha256 "8b3b04c3bb66ceb7c99f67a2b92557dbf252315a4212f2beec5aa9b4c7d2acb0"
    end
  end
  
  depends_on "go" => :build

  def install
    bin.install "gts"
    bin.install "togo"
  end

  test do
    system "#{bin}/gts --version"
  end
end
