# This file was generated by GoReleaser. DO NOT EDIT.
class GtsBio < Formula
  desc "GTS: Genome Transformation Subprograms"
  homepage "https://github.com/go-gts/gts"
  version "0.24.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/go-gts/gts/releases/download/v0.24.4/gts_0.24.4_Darwin_x86_64.tar.gz"
    sha256 "ec358f596cb528ce220d5dd107ff1920766e3ad8715a61c9ee745f270550b518"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/go-gts/gts/releases/download/v0.24.4/gts_0.24.4_Linux_x86_64.tar.gz"
      sha256 "2e4035fac8fccd3fcc75d49afa5edd3cde2ec6605875136ebe15e9ec9f0cdb0e"
    end
  end

  def install
    bin.install "gts"
    bin.install "togo"
    man1.install Dir["man/gts*.1"]
    man7.install Dir["man/gts*.7"]
    bash_completion.install "completion/gts-completion.bash"
    zsh_completion.install "completion/gts-completion.zsh" => "_gts"
  end

  test do
    system "#{bin}/gts --version"
  end
end
